name: Publish

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v2

      - uses: dawidd6/action-download-artifact@v2
        with:
          name: actions_artifacts
          workflow: ${{ github.event.workflow_run.workflow_id }}

      - name: Define PR
        run: |
          echo "PR=$(cat env | grep "prev.event.number" | awk -F '=' '{print $2}')" >> $GITHUB_ENV

      - name: Publish
        run: |
          git config --global user.name "keksobot"
          git config --global user.email "github+keksobot@htmlacademy.ru"
          git fetch --all
          if ! git checkout -t origin/gh-pages
          then
            git checkout --orphan gh-pages
            git rm -rf .
          fi
          rm -rf ${{ env.PR }}
          mv build ${{ env.PR }}
          git add ${{ env.PR }}
          if git commit -m "✔️ Сборка #${{ env.PR }}"
          then
            git push -u origin gh-pages
          else
            echo 'Nothing to commit and push'
          fi
