name: Publish

on:
  - pull_request

jobs:
  start_publish:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Build Project
        run: |
          NODE_ENV=development npm ci && npm run build
          if [[ $(find . -maxdepth 1 -type d -name 'build') == '' ]]
          then
            mkdir build
            cp $(find source -name '*.html') build
            cp -r source/css build
            cp -r source/js build
            cp -r source/fonts build
            cp -r source/img build
          fi

      - name: Publish to Github Pages
        run: |
          pr_number=${{ github.event.number }}
          git config --global user.name "Keks"
          git config --global user.email "keks@htmlacademy.ru"
          git fetch --all
          if ! git checkout -t origin/gh-pages
          then
            git checkout --orphan gh-pages
            git rm -rf .
          fi
          rm -rf ${{ github.event.number }}
          mv build ${{ github.event.number }}
          git add ${{ github.event.number }}
          if git commit -m "✔️ Сборка #${{ github.event.number }}"
          then
            git push -u origin gh-pages
          else
            echo 'Nothing to commit and push'
          fi
