name: Publish

on:
  - pull_request

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Build Project
        run: |
          NODE_ENV=development npm ci && npm run build
          if [[ $(find . -maxdepth 1 -type d -name 'build') == '' ]]
          then
            mkdir build
            cp $(find source -name '*.html') build
            cp -r source/css build
            cp -r source/js build
            cp -r source/fonts build
            cp -r source/img build
          fi

      - name: Publish to Github Pages
        run: |
          git config --global user.name "keksobot"
          git config --global user.email "github+keksobot@htmlacademy.ru"
          git fetch --all
          if ! git checkout -t origin/gh-pages
          then
            git checkout --orphan gh-pages
            git rm -rf .
          fi
          rm -rf ${{ github.event.number }}
          mv build ${{ github.event.number }}
          git add ${{ github.event.number }}
          git commit -m "✔️ Сборка #${{ github.event.number }}"

      - name: push updates
        run: git push -u origin gh-pages
        env:
          github-token: ${{ secrets.GH_ACTION_REPOS_TOKEN }}
